### ISSUE TITLE
commit method on App

### ISSUE THREAD

**Issue by faassen** [morepath/dectate#18]
We should implement a commit method on App. Morepath overrides this anyway to do the recursive commit for mounted apps. This method should be explicitly documented as being intended to support such scenarios (by overriding in subclasses), as opposed to the more low-level dectate.commit which only commits a single class.

See:

https://github.com/morepath/morepath/issues/383

**Comment by faassen** [comment]
This commit method should definitely return an iterable of all applications it committed. Its default implementation could be very simple:

```
  @classmethod
  def commit(cls):
      dectate.commit(cls)
      return [cls]
```

and then we'd let subclasses (like `morepath.App`) override this as long as this contract is followed. Returning the thing committed is important to support the query tool use case.

**Comment by taschini** [comment]
Looks good. morepath.App.commit returns a set, so it must be clear that the contract is to return an iterable and no assumptions should be made on what concrete container is actually returned.

**Comment by faassen** [comment]
I just implemented this.
