### ISSUE TITLE
make topological sort stable

### ISSUE THREAD

**Issue by faassen** [morepath/dectate#20]
It would be nice if topological sort were stable. I don't think it is now entirely, and this can lead to different order of execution of directives and thus different order of execution of registries. This can lead to subtle bugs, see #3 

We should in this case also use this stable topological sort in Morepath itself.

**Comment by faassen** [comment]
So @taschini, I think your test demonstrates that this is indeed stable. It's just that the inputs to it aren't stable as they're the keys of a dict, I think.

**Comment by taschini** [comment]
I agree: it is not an issue arising from the instability of topological_sort itself, but an unpredictability of the ordering of its input.

If that is a problem, it should be enough to enforce a canonical order on the  input before passing to topological_sort.

**Comment by taschini** [comment]
> If that is a problem, it should be enough to enforce a canonical order on the input before passing to topological_sort.

I just realized that no, that's not enough. There is a dependency also on the ordering of get_depend's output.

**Comment by faassen** [comment]
It's less of a problem now that I implemented #3 which bails out if there's an inconsistency.

**Comment by taschini** [comment]
Great.  Then I'd be tempted to inch you towards closing this issue.

**Comment by faassen** [comment]
Okay, closing this.
