### ISSUE TITLE
Phase out autocommit

### ISSUE THREAD

**Issue by taschini** [morepath/dectate#22]
With reference to [morepath#392](https://github.com/morepath/morepath/issues/392), after completing #18 we should phase out autocommit. I suggest we do it in two steps:
1. NOP autocommit and have it raise a DeprecationWarning
2. Finally remove autocommit.

**Comment by faassen** [comment]
One thing we need to get a good story for is the query tool system, which has a `query_auto_tool` API that lets you query all known applications at once, which assumes the auto commit list as well.

Instead the approach should be that `App.commit` always returns an iterable of all the things it committed; by default just the App itself but it could be a list, and that this is then something you can pass into `query_tool`.

**Comment by faassen** [comment]
I can't noop autocommit as in this case Dectate would break -- unlike Morepath it does not commit on first use, after all. But I can just introduce the deprecation warning first so we have a transition.

**Comment by faassen** [comment]
I'm done with adding the deprecation warnings and have created issue #24 and #25 for it. Moving this one along to 0.11 when we can remove stuff, including the whole global list of apps.

**Comment by taschini** [comment]
Is there anything left to do here?

**Comment by faassen** [comment]
No, I think this is done now.
