### ISSUE TITLE
directive directive confusing

### ISSUE THREAD

**Issue by faassen** [morepath/dectate#37]
When you use the `directive` directive, you need to make sure that the module it is in is imported before you scan any other code. This can be surprising, as you might expect it works like any other Dectate directive, where import order is immaterial.

Perhaps this implies the `directive` directive shouldn't be a directive at all. Directives are really like methods. Perhap we should install them like methods on the `App` class, like this:

```
class App(dectate.App):
     foo = dectate.directive(FooAction)
```

If we make this the way to install directives, we would have no more import issues, as it's impossible to use a new directive without importing its app class first.

What do you think, @href, @taschini?

**Comment by href** [comment]
I'm +1, since it documents the directives introduced on any given application. Currently I can introduce the foo directive three folders down if I want to be difficult. Not that this stops me, but the convention would favour a clearly documented list of directives introduced on each application.

**Comment by taschini** [comment]
I don't have yet an opinion on this.  I don't use the `scan` / `autoscan` machinery, so I'm always in control of the import sequence.

**Comment by faassen** [comment]
This is in my mind unrelated to autoscan. If you want to use a directive that's defined on an app class, it's odd to have to import some other entirely different module before you do so. We could make this oddness go away if we defined these things as methods.

**Comment by faassen** [comment]
Now as to technical difficulties. I tried to implement this but ran into some difficulties. I'd like it to look like this:

```
class App(dectate.App):
     foo = dectate.directive(FooAction)
```

So, `dectate.directive` should return a classmethod and things would be over with then. Unfortunately there are some difficulties with its implementation:
- the name of the directive is needed in `directive` - in particular to obtain the logger, and to construct log messages. It's also used to set up the appropriate `__name__` (or `__qualname__`) of the method, but this may not be needed anymore, not sure.
- the `directive` directive does a `register_action_class` on the dectate object, and the dectate object is obtained from the class. But there is no access to the class during method definition time (the method itself can have access to the class as it's a classmethod).

I can make it all work by making `directive` be a descriptor with a `__get__`, but that introduces rather a lot of magic in a case where I was hoping to simplify. I'll continue trying a few options.

**Comment by faassen** [comment]
I realized that I could scan a dectate App subclass  for directives and do `register_action_class` during commit . This should also let me extract the name in time and attach it to the directive object after the fact; I'm rewriting the tests and I'll see what else I run into.
