### ISSUE TITLE
Change commit signature

### ISSUE THREAD

**Issue by href** [morepath/dectate#8]
Using the commit function I kind of wished it worked like this:

```
commit(App)
```

Or

```
commit(App1, App2)
```

Instead of

```
commit([App])
```

Really, really minor point, but since committing a single app during tests seems to be the main use case for this function I think we should get rid of the array:

```
def commit(*apps):
    # ...
```

**Comment by faassen** [comment]
I think this is a good idea; the list signature of commit bothered me a bit but somehow I didn't think of this solution. Maybe too much JS on the brain recently. I'll go change it.
